version: '3.9'

volumes:
  blog_content:
  postgres_data:

services:
  db:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      retries: 10

    deploy:
      resources:
        limits:
          memory: 128M    # Max usage
          cpus: '0.05'

  backend:
    image: alexeyzaliznuak/chat_boty_backend_dev
    env_file: .env

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - blog_content:/app/data

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
      resources:
        limits:
          memory: 300M    # Max usage
          cpus: '0.2'

  frontend:
    image: maxiq/chat_boty_frontend_dev
    env_file: .env

    deploy:
      resources:
        limits:
          memory: 666M    # Max usage
        reservations:
          memory: 256M    # Reserve

  nginx:
    image: nginx:1.19.3
    ports:
      - "${NGINX_PORT}:80"

    depends_on:
      - backend
      - frontend

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
