version: "3.8"

volumes:
  static:
  postgres_data:

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./chat-boty-backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file: .env
    depends_on:
      - db

  frontend:
    build: ./chat-boty-client
    env_file: .env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
