version: '3'

volumes:
  static:
  blog_content:
  postgres_data:

services:
  db:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      retries: 10


  backend:
    build: ./chat-boty-backend
    env_file: .env

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - blog_content:/app/data

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5


  frontend:
    build: ./chat-boty-client
    env_file: .env


  nginx:
    image: nginx:1.19.3
    ports:
      - "${NGINX_PORT}:80"

    depends_on:
      - backend
      - frontend

    volumes:
      - static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
