volumes:
  static:
  postgres_data:

services:
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./chat-boty-backend
    env_file: .env
    depends_on:
      - db

  frontend:
    build: ./chat-boty-client
    env_file: .env

  nginx:
    image: nginx:1.19.3
    depends_on:
      - backend
      - frontend
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
